export type PlatformImageCategory = "consoles" | "computers" | "handhelds" | "arcade";

export type PlatformCatalogEntry = {
  name: string;
  slug: string;
  category: PlatformImageCategory;
  lightImageName: string;
  darkImageName: string;
  fileExtensions: string[];
  namingStandard: "no-intro" | "redump" | "none";
  versionSource: "titledb" | "no-intro" | "redump" | "none";
  torznabCategories: string;
  igdbPlatformId: number | null;
};

export const PLATFORM_CATALOG: PlatformCatalogEntry[] = [
  {
    name: "3DO Interactive Multiplayer",
    slug: "3do-interactive-multiplayer",
    category: "consoles",
    lightImageName: "3DO Interactive Multiplayer",
    darkImageName: "3DO Interactive Multiplayer",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Atari 2600",
    slug: "atari-2600",
    category: "consoles",
    lightImageName: "Atari 2600",
    darkImageName: "Atari 2600",
    fileExtensions: ["a26", "bin"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Atari 5200",
    slug: "atari-5200",
    category: "consoles",
    lightImageName: "Atari 5200",
    darkImageName: "Atari 5200",
    fileExtensions: ["a52", "bin"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Atari 7800",
    slug: "atari-7800",
    category: "consoles",
    lightImageName: "Atari 7800",
    darkImageName: "Atari 7800",
    fileExtensions: ["a78", "bin"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Atari Jaguar",
    slug: "atari-jaguar",
    category: "consoles",
    lightImageName: "Atari Jaguar",
    darkImageName: "Atari Jaguar",
    fileExtensions: ["j64", "jag"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo DSi",
    slug: "nintendo-dsi",
    category: "handhelds",
    lightImageName: "Nintendo DSi",
    darkImageName: "Nintendo DSi",
    fileExtensions: ["nds"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Atari Lynx",
    slug: "atari-lynx",
    category: "handhelds",
    lightImageName: "Atari Lynx",
    darkImageName: "Atari Lynx",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "ColecoVision",
    slug: "colecovision",
    category: "consoles",
    lightImageName: "ColecoVision",
    darkImageName: "ColecoVision",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "WonderSwan",
    slug: "wonderswan",
    category: "handhelds",
    lightImageName: "WonderSwan",
    darkImageName: "WonderSwan",
    fileExtensions: ["ws"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Wonderswan Color",
    slug: "wonderswan-color",
    category: "handhelds",
    lightImageName: "Wonderswan Color",
    darkImageName: "Wonderswan Color",
    fileExtensions: ["wsc"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Microsoft Xbox",
    slug: "microsoft-xbox",
    category: "consoles",
    lightImageName: "Microsoft Xbox",
    darkImageName: "Microsoft Xbox",
    fileExtensions: ["iso", "xiso"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: null,
  },
  {
    name: "Microsoft Xbox 360",
    slug: "microsoft-xbox-360",
    category: "consoles",
    lightImageName: "Microsoft Xbox 360",
    darkImageName: "Microsoft Xbox 360",
    fileExtensions: ["iso"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: null,
  },
  {
    name: "NEC PC Engine",
    slug: "nec-pc-engine",
    category: "consoles",
    lightImageName: "NEC PC Engine",
    darkImageName: "NEC PC Engine",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "NEC PC Engine CD",
    slug: "nec-pc-engine-cd",
    category: "consoles",
    lightImageName: "NEC PC Engine CD",
    darkImageName: "NEC PC Engine CD",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "NEC PC Engine SuperGrafx",
    slug: "nec-pc-engine-supergrafx",
    category: "consoles",
    lightImageName: "NEC PC Engine SuperGrafx",
    darkImageName: "NEC PC Engine SuperGrafx",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "NEC PC-FX",
    slug: "nec-pc-fx",
    category: "consoles",
    lightImageName: "NEC PC-FX",
    darkImageName: "NEC PC-FX",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "NEC TurboGrafx-16",
    slug: "nec-turbografx-16",
    category: "consoles",
    lightImageName: "NEC TurboGrafx-16",
    darkImageName: "NEC TurboGrafx-16",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "NEC TurboGrafx-CD",
    slug: "nec-turbografx-cd",
    category: "consoles",
    lightImageName: "NEC TurboGrafx-CD",
    darkImageName: "NEC TurboGrafx-CD",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo 3DS",
    slug: "3ds",
    category: "handhelds",
    lightImageName: "Nintendo 3DS",
    darkImageName: "Nintendo 3DS",
    fileExtensions: ["cia", "3ds"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 37,
  },
  {
    name: "Nintendo 64",
    slug: "n64",
    category: "consoles",
    lightImageName: "Nintendo 64",
    darkImageName: "Nintendo 64",
    fileExtensions: ["n64", "z64", "v64"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 4,
  },
  {
    name: "Nintendo DS",
    slug: "nds",
    category: "handhelds",
    lightImageName: "Nintendo DS",
    darkImageName: "Nintendo DS",
    fileExtensions: ["nds"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 20,
  },
  {
    name: "Nintendo Entertainment System",
    slug: "nintendo-entertainment-system",
    category: "consoles",
    lightImageName: "Nintendo Entertainment System",
    darkImageName: "Nintendo Entertainment System",
    fileExtensions: ["nes", "fds"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Famicom",
    slug: "nintendo-famicom",
    category: "consoles",
    lightImageName: "Nintendo Famicom",
    darkImageName: "Nintendo Famicom",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Famicom Disk System",
    slug: "nintendo-famicom-disk-system",
    category: "consoles",
    lightImageName: "Nintendo Famicom Disk System",
    darkImageName: "Nintendo Famicom Disk System",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Game Boy",
    slug: "gb",
    category: "handhelds",
    lightImageName: "Nintendo Game Boy",
    darkImageName: "Nintendo Game Boy",
    fileExtensions: ["gb"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 33,
  },
  {
    name: "Nintendo Game Boy Advance",
    slug: "gba",
    category: "handhelds",
    lightImageName: "Nintendo Game Boy Advance",
    darkImageName: "Nintendo Game Boy Advance",
    fileExtensions: ["gba"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 24,
  },
  {
    name: "Nintendo Game Boy Color",
    slug: "gbc",
    category: "handhelds",
    lightImageName: "Nintendo Game Boy Color",
    darkImageName: "Nintendo Game Boy Color",
    fileExtensions: ["gbc"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 22,
  },
  {
    name: "Nintendo GameCube",
    slug: "nintendo-gamecube",
    category: "consoles",
    lightImageName: "Nintendo GameCube",
    darkImageName: "Nintendo GameCube",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Switch",
    slug: "switch",
    category: "consoles",
    lightImageName: "Nintendo Switch",
    darkImageName: "Nintendo Switch",
    fileExtensions: ["nsp", "nsz", "xci", "xcz"],
    namingStandard: "none",
    versionSource: "titledb",
    torznabCategories: "6000,6070",
    igdbPlatformId: 130,
  },
  {
    name: "Nintendo Virtual Boy",
    slug: "nintendo-virtual-boy",
    category: "consoles",
    lightImageName: "Nintendo Virtual Boy",
    darkImageName: "Nintendo Virtual Boy",
    fileExtensions: ["vb"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Wii",
    slug: "nintendo-wii",
    category: "consoles",
    lightImageName: "Nintendo Wii",
    darkImageName: "Nintendo Wii",
    fileExtensions: ["iso", "wbfs", "rvz", "nkit"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: null,
  },
  {
    name: "Nintendo Wii U",
    slug: "nintendo-wii-u",
    category: "consoles",
    lightImageName: "Nintendo Wii U",
    darkImageName: "Nintendo Wii U",
    fileExtensions: ["wud", "wux", "iso"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6050",
    igdbPlatformId: null,
  },
  {
    name: "Sega SG-1000",
    slug: "sega-sg-1000",
    category: "consoles",
    lightImageName: "Sega SG-1000",
    darkImageName: "Sega SG-1000",
    fileExtensions: ["sg"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sega 32X",
    slug: "sega-32x",
    category: "consoles",
    lightImageName: "Sega 32X",
    darkImageName: "Sega 32X",
    fileExtensions: ["32x", "bin"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sega CD",
    slug: "sega-cd",
    category: "consoles",
    lightImageName: "Sega CD",
    darkImageName: "Sega CD",
    fileExtensions: ["cue", "bin", "iso", "chd"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sega Dreamcast",
    slug: "dreamcast",
    category: "consoles",
    lightImageName: "Sega Dreamcast",
    darkImageName: "Sega Dreamcast",
    fileExtensions: ["gdi", "chd"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6080",
    igdbPlatformId: 23,
  },
  {
    name: "Sega Game Gear",
    slug: "sega-game-gear",
    category: "handhelds",
    lightImageName: "Sega Game Gear",
    darkImageName: "Sega Game Gear",
    fileExtensions: ["gg"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sega Genesis",
    slug: "genesis",
    category: "consoles",
    lightImageName: "Sega Genesis",
    darkImageName: "Sega Genesis",
    fileExtensions: ["md", "bin", "smd"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 29,
  },
  {
    name: "Sega Master System",
    slug: "sega-master-system",
    category: "consoles",
    lightImageName: "Sega Master System",
    darkImageName: "Sega Master System",
    fileExtensions: ["sms"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sega Saturn",
    slug: "sega-saturn",
    category: "consoles",
    lightImageName: "Sega Saturn",
    darkImageName: "Sega Saturn",
    fileExtensions: ["cue", "bin", "iso", "chd"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "SNK Neo Geo",
    slug: "snk-neo-geo",
    category: "consoles",
    lightImageName: "SNK Neo Geo",
    darkImageName: "SNK Neo Geo",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "SNK Neo Geo CD",
    slug: "snk-neo-geo-cd",
    category: "consoles",
    lightImageName: "SNK Neo Geo CD",
    darkImageName: "SNK Neo Geo CD",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "SNK Neo Geo Pocket",
    slug: "snk-neo-geo-pocket",
    category: "handhelds",
    lightImageName: "SNK Neo Geo Pocket",
    darkImageName: "SNK Neo Geo Pocket",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "SNK Neo Geo Pocket Color",
    slug: "snk-neo-geo-pocket-color",
    category: "handhelds",
    lightImageName: "SNK Neo Geo Pocket Color",
    darkImageName: "SNK Neo Geo Pocket Color",
    fileExtensions: ["zip", "7z"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6080",
    igdbPlatformId: null,
  },
  {
    name: "Sony Playstation",
    slug: "ps1",
    category: "consoles",
    lightImageName: "Sony Playstation",
    darkImageName: "Sony Playstation",
    fileExtensions: ["bin", "cue", "iso", "chd"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: 7,
  },
  {
    name: "Sony Playstation 2",
    slug: "ps2",
    category: "consoles",
    lightImageName: "Sony Playstation 2",
    darkImageName: "Sony Playstation 2",
    fileExtensions: ["iso", "chd"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: 8,
  },
  {
    name: "Sony Playstation 3",
    slug: "sony-playstation-3",
    category: "consoles",
    lightImageName: "Sony Playstation 3",
    darkImageName: "Sony Playstation 3",
    fileExtensions: ["iso", "pkg"],
    namingStandard: "redump",
    versionSource: "redump",
    torznabCategories: "6000,6050",
    igdbPlatformId: null,
  },
  {
    name: "Sony PS Vita",
    slug: "sony-ps-vita",
    category: "handhelds",
    lightImageName: "Sony PS Vita",
    darkImageName: "Sony PS Vita",
    fileExtensions: ["vpk"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6060",
    igdbPlatformId: null,
  },
  {
    name: "Sony PSP",
    slug: "psp",
    category: "handhelds",
    lightImageName: "Sony PSP",
    darkImageName: "Sony PSP",
    fileExtensions: ["iso", "cso", "chd"],
    namingStandard: "none",
    versionSource: "none",
    torznabCategories: "6000,6060",
    igdbPlatformId: 38,
  },
  {
    name: "Super Nintendo Entertainment System",
    slug: "snes",
    category: "consoles",
    lightImageName: "Super Nintendo Entertainment System",
    darkImageName: "Super Nintendo Entertainment System",
    fileExtensions: ["sfc", "smc"],
    namingStandard: "no-intro",
    versionSource: "no-intro",
    torznabCategories: "6000,6080",
    igdbPlatformId: 19,
  },
];

export const PLATFORM_CATALOG_BY_SLUG = new Map(
  PLATFORM_CATALOG.map((entry) => [entry.slug, entry])
);
